// src/components/signup.form/email.signup-form.tsx
import { component$, PropFunction, useStore, useStylesScoped$ } from '@builder.io/qwik';
import styles from './header.css?inline';

export interface EmailSignupFormProps {
    value?: string;
    onValue$: PropFunction<(eventName: string, value: unknown) => unknown>;
}

export default component$<EmailSignupFormProps>((props: EmailSignupFormProps) => {
    // useStylesScoped$(styles);
    const store = useStore({ email: props.value, })
    return (
        <form class="grid grid-cols-1 mt-8 md:grid-cols-1">
            {/* <!-- Email input --> */}
            <div class="mb-6">
                {/* <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Email address</label> */}
                <input
                    type="email"
                    id="email"
                    pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$"
                    title="Missing domain name. Please include domain name"
                    size={30}
                    required
                    class="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                    placeholder="Email address"
                    onInput$={(e: Event) => store.email = (e.target as HTMLInputElement).value}
                />
            </div>

            {/* <!-- Submit button --> */}
            <button
                type='button'
                class="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out w-full"
                data-mdb-ripple="true"
                data-mdb-ripple-color="light"
                onClick$={() => {
                    if (typeof props.onValue$ === 'function') props.onValue$('value', store.email);
                }}
            >
                Next
            </button>

            <div
                class="flex items-center my-4 before:flex-1 before:border-t before:border-gray-300 before:mt-0.5 after:flex-1 after:border-t after:border-gray-300 after:mt-0.5"
            >
                <p class="text-center font-semibold mx-4 mb-0">OR</p>
            </div>

            <a
                class="px-7 py-3 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out w-full flex justify-center items-center mb-3"
                style="background-color: #3b5998"
                href="#!"
                role="button"
                data-mdb-ripple="true"
                data-mdb-ripple-color="light"
            >
                {/* <!-- Gmail --> */}
                <svg xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                    class="w-3.5 h-3.5 mr-2">
                    {/* <!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --> */}
                    <path fill="currentColor" d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z" /></svg>
                Continue with Gmail
            </a>
            {/* <!-- Twitter --> */}
            {/* <a
        class="px-7 py-3 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out w-full flex justify-center items-center"
        style="background-color: #55acee"
        href="#!"
        role="button"
        data-mdb-ripple="true"
        data-mdb-ripple-color="light"
    >
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 512 512"
            class="w-3.5 h-3.5 mr-2"
        >
            <path
                fill="currentColor"
                d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"
            /></svg>Continue with Twitter
    </a> */}
        </form>
    );
});

// src/components/signup/email.signup-form.vue
<script lang="ts">
export default { name: "EmailSignupForm" };
</script>
<script setup lang="ts">
import { ref, watch, reactive } from "vue";
import { TransitionRoot } from "@headlessui/vue";

const props = defineProps<{ email: string }>();

const emit = defineEmits<{
  (event: "update:email", v: string): void;
  (event: "on-submit", v: string): void;
  (event: "on-signup-google", v: string): void;
}>();

const errs = reactive({ email: "" });

watch(props, async (newValue, oldValue) => {
  if (!props.email) errs.email = "empty";
  else errs.email = "";
});

function submitHandler() {
  if (errs.email) return;
  emit("on-submit", props.email || "");
}

function submitGoogleHandler() {
  emit("on-signup-google", props.email || "");
}
</script>

<template>
  <form @submit.prevent="submitHandler">
    <TransitionRoot
      appear
      show
      enter="transform transition duration-[400ms] ease-in-out"
      enter-from="translate-x-1/4 opacity-0"
      enter-to="translate-x-0 opacity-100"
      leave="transform duration-200 transition ease-in-out"
      leave-from="translate-x-1/4 opacity-100"
      leave-to="translate-x-full opacity-0"
    >
      <div class="grid grid-flow-row gap-10">
        <div class="grid grid-flow-row gap-3">
          <div>
            <h1 class="text-5xl font-bold">Looks like</h1>
            <h1 class="text-5xl font-bold">you are new!</h1>
          </div>

          <p class="text-gray-800">
            Please enter your email address and password to sign up.
          </p>
        </div>

        <div class="grid grid-flow-row gap-3">
          <!-- Email input -->
          <div>
            <input
              type="email"
              id="email"
              :value="email"
              @input="(e: any) => emit('update:email', e.target.value)"
              class="block w-full p-4 text-gray-900 border border-gray-300 rounded-xl bg-gray-50 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Enter your email"
              size="30"
              required
            />
            <span
              v-if="errs.email === 'empty'"
              class="mt-2 text-sm text-red-600 dark:text-red-500"
              >Email is required</span
            >
          </div>

          <!-- <div
          class="flex items-center my-4 before:flex-1 before:border-t before:border-gray-300 before:mt-0.5 after:flex-1 after:border-t after:border-gray-300 after:mt-0.5"
        >
          <p class="text-center font-semibold mx-4 mb-0">OR</p>
        </div>

        <a
          class="px-7 py-3 text-white font-medium text-sm leading-snug uppercase rounded-full shadow-md hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out w-full flex justify-center items-center mb-3"
          style="background-color: #3b5998"
          href="#!"
          role="button"
          data-mdb-ripple="true"
          data-mdb-ripple-color="light"
          @click="submitGoogleHandler"
        >
          <IconGmail></IconGmail>
          Signup with Gmail
        </a> -->
        </div>

        <!-- Submit button -->
        <button
          type="submit"
          class="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out w-full"
          data-mdb-ripple="true"
          data-mdb-ripple-color="light"
        >
          Next
        </button>
      </div>
    </TransitionRoot>

    <div class="text-center pt-10">
      <p>
        Already have an account?
        <a href="/signin" class="text-blue-500 font-semibold">Signin</a>
      </p>
    </div>
  </form>
</template>
